services:
  backend:
    build:
      context: ./Product managment/backend/src/System  
    ports:
      - "8080:8080"                       
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  
    depends_on:
      - db            

  frontend:
    build:
      context: ./Product managment/frontend/src/System
    ports:
      - "3000:8080"
    environment:
     - ASPNETCORE_ENVIRONMENT=Development

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=rj9UKgmw8
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql  

volumes:
  db_data:  
